services:
  - type: web
    name: liveplay
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/bein-channels
    autoDeploy: true
